#!/bin/bash

echo "🔍 Debugging Android TTS - Follow these steps:"
echo ""
echo "1️⃣  Run the app on emulator/device"
echo ""
echo "2️⃣  In Android Studio, open 'Logcat' panel (View > Tool Windows > Logcat)"
echo ""
echo "3️⃣  In the Logcat filter box, type: TTSManager"
echo ""
echo "4️⃣  Click the 'Reset AI' button in the app menu"
echo ""
echo "5️⃣  Look for these log messages:"
echo ""
echo "✅ GOOD - TTS is ready:"
echo "   TTSManager: Starting TTS initialization..."
echo "   TTSManager: ✅ TTS ready! Language: Chinese"
echo "   TTSManager: 🗣️ Speaking..."
echo "   TTSManager: 🔊 Speech started"
echo ""
echo "❌ BAD - TTS failed:"
echo "   TTSManager: TTS initialization callback received with status: -1"
echo "   TTSManager: ❌ TTS initialization failed"
echo "   (You should also see an error dialog)"
echo ""
echo "⚠️  VOLUME ISSUE:"
echo "   TTSManager: ⚠️ Media volume is MUTED!"
echo "   → Press Volume UP on emulator"
echo ""
echo "6️⃣  Common emulator issue:"
echo "   Android emulators often DON'T have Google TTS installed"
echo "   → Test on a REAL device for best results"
echo "   → Or install 'Google Text-to-Speech' from Play Store on emulator"
echo ""
echo "7️⃣  Share the Logcat output here so I can help debug!"
