/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package tailscalebridge */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "bridge.go"

#include <jni.h>
#include <stdlib.h>
#include <android/log.h>

static jstring newStringUTF(JNIEnv* env, const char* str) {
    if (str == NULL) return NULL;
    return (*env)->NewStringUTF(env, str);
}

static const char* getStringBytes(JNIEnv* env, jstring jstr) {
    if (jstr == NULL) return NULL;
    return (*env)->GetStringUTFChars(env, jstr, NULL);
}

static void releaseStringBytes(JNIEnv* env, jstring jstr, const char* str) {
    if (jstr == NULL || str == NULL) return;
    (*env)->ReleaseStringUTFChars(env, jstr, str);
}

static void android_log(const char* msg) {
    __android_log_write(ANDROID_LOG_DEBUG, "TailscaleBridge", msg);
}

__attribute__((constructor))
static void init_env() {
    setenv("TS_DEBUG_NO_NETLINK", "1", 1);
    setenv("TS_NO_EXTERNAL_CONFIG", "1", 1);
    setenv("TS_PORTABLE_NETSTACK", "1", 1);
    setenv("TS_NO_SYSNETWORK_CONNS", "1", 1);
    setenv("TS_DEBUG_NO_ROUTING", "1", 1);
    setenv("TS_DEBUG_IGNORE_NETLINK_ERRORS", "1", 1);
    setenv("TS_DEBUG_WITHOUT_NETMON", "1", 1);
    setenv("TS_DEBUG_ALWAYS_USE_NETSTACK", "1", 1);
    setenv("TS_DEBUG_NO_LINUX_NETLINK", "1", 1);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern jstring Java_com_quantumproperty_qcai_native_TailscaleBridge_connect(JNIEnv* env, jobject obj, jstring authKey, jstring hostname, jstring stateDir);
extern jstring Java_com_quantumproperty_qcai_native_TailscaleBridge_getIP(JNIEnv* env, jobject obj);
extern jstring Java_com_quantumproperty_qcai_native_TailscaleBridge_getState(JNIEnv* env, jobject obj);
extern void Java_com_quantumproperty_qcai_native_TailscaleBridge_disconnect(JNIEnv* env, jobject obj);

#ifdef __cplusplus
}
#endif
